# cd-test.yml
# ~~~~~~~~~~~~~~
#
# Mobile app build and deploy pipeline that deploys iOS and Android Test
# apps to App Center. 
# The pipeline must be manually triggered.

trigger:
- none

pr:
- none

variables:
  solution: '**/*.sln'
  versionName: 2.2
  env: ${{ replace( variables['Build.DefinitionName'], '-cd-build-deploy-appcenter', '') }}
      
name: $(Build.Reason)-$(versionName).$(Build.BuildId).$(env)

extends:
  template: cd-build-deploy-appcenter.yml
  parameters:
    solution: ${{ variables.solution }}
    versionName: ${{ variables.versionName }}
    env: ${{ variables.env }}
    doBuild: true
    doDeploy: false
