trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'

variables:
  - group: Appcenter-${{ parameters.env }}

extends:
  template: cd-release-text-pipeline.yml
  parameters:
    azureSubscription: FHI-Koronasertifikat.Verifisering-ARM-Test
    accountName: $(stvksAccountname)
    textVersion: '3.4'
